[package]
name = "github_branch_table"
version = "0.1.0"
authors = ["Zero <https://github.com/ZeroErrors>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
clap = "3.0"
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
prettytable-rs = "0.8"
